name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            platform: osx-x64
            artifact_name: sql2fs
            asset_name: sql2fs-linux-x64
          - os: ubuntu-latest
            name: win
            platform: win-x64
            artifact_name: sql2fs.exe
            asset_name: sql2fs-win-x64.exe
          - os: ubuntu-latest
            name: macos
            platform: osx-x64
            artifact_name: sql2fs
            asset_name: sql2fs-macos-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -r ${{ matrix.platform }} /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/sql2fs/sql2fs/bin/Debug/net5.0/${{ matrix.platform }}/publish/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true